name=calculate_LSBs
version=1.0.0
author=joro1957
maintainer=joro1957 <joro_1957@outlook.com>
sentence="Simple library for calculating LSB's & shunt Ohms for ADC's & voltage dividers using external measurements/multimeters."
paragraph="Simple library for calculating LSB's & shunt Ohms for ADC's & voltage dividers using external measurements/multimeters."
category=Signal Input/Output
url=https://github.com/joro1957/calculate_LSBs
architectures=*
includes=calculate_LSBs.h
